blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('profile/<str:username>/', views.post_list, name='post_list'),
    # path('<int:id>/', views.post_list, name='post_list'),
    path('latest/', views.all_list, name='all_list'),
    path('success/<str:username>/', views.add_user, name='add_user'),
    path('news/', views.subs_news_list, name='news_list'),
    path('successtodelete/<str:username>/', views.delete_user, name='delete_user'),
    path('home/', views.home, name='home'),
    path('add/', views.post_create, name='post_create'),
    path('alreadyread/<int:post_id>', views.already_read, name='already_read'),
]

nekidaem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='posts', verbose_name='Пользователь',
                             on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    text = models.TextField(verbose_name='Текст')
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    id = models.AutoField(primary_key=True)

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class UserFollowing(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='following_posts', verbose_name='Пользователь',
                             on_delete=models.CASCADE)
    following = models.ForeignKey(User, related_name='followed_by', on_delete=models.CASCADE)

class AlreadyRead(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='user_read', verbose_name='Пользователь',
                             on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name='read_id', on_delete=models.CASCADE)

blog/forms.py
from django import forms
from .models import Post


class PostCreationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(PostCreationForm, self).__init__(*args, **kwargs)
    class Meta:
        model = Post
        fields = ('title', 'text')
        exclude = ('user',)

blog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from blog.forms import PostCreationForm
from blog.models import Post, UserFollowing, AlreadyRead
from django.core.mail import send_mail


def home(request):
    # if username:
    posts = Post.objects.filter(user=request.user)
    return render(request, 'blog/home.html',
                  {'posts': posts})


def post_list(request, username):
    # if username:
    post_owner = get_object_or_404(User, username=username)
    posts = Post.objects.filter(user=post_owner)
    return render(request, 'blog/list.html',
                  {'posts': posts})


def all_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'blog/all.html',
                  {'posts': posts})


@login_required
def add_user(request, username):
    user_to_follow = get_object_or_404(User, username=username)
    user = User.objects.get(id=request.user.id)
    UserFollowing.objects.get_or_create(user=request.user, following=user_to_follow)
    return render(request, 'blog/success.html', {'username': user_to_follow})


@login_required
def delete_user(request, username):
    user_to_follow = get_object_or_404(User, username=username)
    user = User.objects.get(id=request.user.id)
    UserFollowing.objects.filter(user=request.user, following=user_to_follow).delete()
    return render(request, 'blog/success_to_delete.html', {'username': user_to_follow})


@login_required
def subs_news_list(request):
    # user = User.objects.get(id=request.user.id)
    qs = UserFollowing.objects.filter(user=request.user).values_list('following', flat=True)
    lst_of_ids = list(qs)
    ar_qs = AlreadyRead.objects.filter(user=request.user).values_list('post_id', flat=True)
    lst_of_ar = list(ar_qs)
    posts = Post.objects.filter(user__in=lst_of_ids).exclude(id__in=lst_of_ar).order_by('-date')
    return render(request, 'blog/news.html',
                  {'posts': posts})


@login_required
def already_read(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    AlreadyRead.objects.get_or_create(user=request.user, post=post)
    ar_qs = AlreadyRead.objects.filter(user=request.user).values_list('post_id', flat=True)
    lst_of_ar = list(ar_qs)
    qs = UserFollowing.objects.filter(user=request.user).values_list('following', flat=True)
    lst_of_ids = list(qs)
    posts = Post.objects.filter(user__in=lst_of_ids).exclude(id__in=lst_of_ar).order_by('-date')
    return render(request, 'blog/news.html',
                  {'posts': posts})


@login_required
def post_create(request):
    user = request.user
    qs = UserFollowing.objects.filter(following=request.user).values_list('user', flat=True)
    lst_of_ids = list(qs)
    if request.method == 'POST':
        # Форма отправлена.
        form = PostCreationForm(request.POST, user=request.user)
        if form.is_valid():
            # Данные формы валидны.
            # img = form.cleaned_data.get("image")
            cd = form.cleaned_data
            new_item = form.save(commit=False)
            new_item.user = request.user
            # Добавляем пользователя к созданному объекту.
            new_item.save()
            mail_host = "localhost"
            user_list = User.objects.filter(id__in=lst_of_ids)
            recipients = []
            for user in user_list:
                recipients.append(user.email)
            message = 'У пользователя {0} в блоге появилась новая запись!'.format(user)
            subject = 'Новый пост'
            send_mail(subject, message, mail_host, recipients, fail_silently=False)
            return redirect("/home/")
    else:
        # Заполняем форму данными из GET-запроса.
        form = PostCreationForm(user=request.user)
    return render(request,
                  'blog/create.html',
                  {'form': form})

blog/templates/blog/all.html
{% extends "blog/base.html" %}

{% block title %}
{% endblock %}
{% block content %}
{% for post in posts %}
<h1>{{ post.title }}</h1>
<a href="{% url 'blog:post_list' username=post.user.username %}">{{ post.user }}</a>

<br>
{{ post.text }}
<br>
{{ post.date }}

{% endfor %}
{% endblock %}

blog/templates/blog/base.html
{% url 'blog:all_list' as all_url%}
{% url 'blog:news_list' as news_url%%}
{% url 'blog:post_create' as create_url%}

<!DOCTYPE HTML>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
    <title>{% block title %}Nekidaem{% endblock %}</title>
</head>
<body>
     <nav class="navbar navbar-expand-lg navbar-light container" style="background-color: #e3f2fd;">
      <a href="{% url 'blog:home' %}">My Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item {% if request.path == all_url%}active {% endif %}	">
              <a class="nav-link" href="{% url 'blog:all_list'%}">Latest</a>
          <li class="nav-item {% if request.path == news_url%}active {% endif %}">
            <a class="nav-link" href="{% url 'blog:news_list'%}">News</a>
          </li>
            {% if user.is_authenticated%}
          <li class="nav-item
           {% if request.path == create_url%} active {% endif %}">
            <a class="nav-link" href="{% url 'blog:post_create'%}">Create a Post</a>
          </li>

            {% endif %}

        </ul>
      </div>
    </nav>
     <div class="container">
{% if request.user.is_authenticated %}
    Hello {{ request.user }},
{% endif %}
</div>
      <div class="container">
        {% block content %}{% endblock %}
      </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  <script>
    $(document).ready(function() {
        $('.js-example-basic-single').select2();
        $('.js-example-basic-multiple').select2();
    });
  </script>
  </body>
</html>

blog/templates/blog/create.html
{% extends "blog/base.html" %}
{% block title %}Create a post{% endblock %}
{% block content %}
    <h1>Create a post</h1>
    <form action="." method="post" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Upload it!">
    </form>
{% endblock %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}

{% block title %}
{% endblock %}
{% block content %}

{% for post in posts %}
<h1>{{ post.title }}</h1>
{{ post.text }}
<br>
{{ post.date }}
{% endfor %}

{% endblock %}

blog/templates/blog/list.html
{% extends "blog/base.html" %}

{% block title %}
{% endblock %}
{% block content %}

{% for post in posts %}
<h1>{{ post.title }}</h1>
<a href="{% url 'blog:add_user' post.user%}">Subscribe</a>
<a href="{% url 'blog:delete_user' post.user%}">Unsubsсribe</a>
{{ post.text }}
<br>
{{ post.date }}
{% endfor %}

{% endblock %}

blog/templates/blog/news.html
{% extends "blog/base.html" %}

{% block title %}
{% endblock %}
{% block content %}

{% for post in posts %}
<h1>{{ post.title }}</h1>
{{ post.text }}
<br>
<a href="{% url 'blog:add_user' post.user%}">{{ post.user }}</a>
{{ post.date }}
<a href="{% url 'blog:already_read' post.id%}">Already read</a>
{% endfor %}

{% endblock %}

blog/templates/blog/success.html
{% extends "blog/base.html" %}
{% block title %}
{% endblock %}
{% block content %}
    You successfully subscribed
{% endblock %}

blog/templates/blog/success_to_delete.html
{% extends "blog/base.html" %}
{% block title %}
{% endblock %}
{% block content %}
    You successfully unsubscribed
{% endblock %}